/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import com.agents.DynamicAgent
import com.agents.Wolf
import com.board.BoardManager
import com.game.Game
import com.game.container.ContainerFactory
import com.game.settings.DirectionKeys
import java.util.Arrays
import kotlin.random.Random

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val containerFactory = ContainerFactory(10)
    val game = Game(containerFactory.constructContainer("HARD")!!)
    game.start(System.`in`.reader(), System.out.writer())
}
